### ISSUE TITLE
Contributing fixes?

### ISSUE THREAD

**Issue by hmijail** [opendtrace/toolkit#6]
Hello, 

I have some bugfixes and improvements to dapptrace, as provided in Mac OS X 10.11.6 (dtrace -V reports Sun D 1.12.1)
I would like to contribute my changes. Is there any procedure to follow? Or is a Pull Request enough?

**Comment by gvnn3** [comment]
Yes, please create a pull request.

**Comment by hmijail** [comment]
Please remember to merge the pull requests :)
