### ISSUE TITLE
Latest version of everything

### ISSUE THREAD

**Issue by dewi-ny-je** [opendtrace/toolkit#9]
I was checking DTrace website
http://www.brendangregg.com/dtracetoolkit.html
and it states that the latest version is here, but iosnoop is, for example, much older here than on http://www.brendangregg.com/DTrace/iosnoop

Maybe these are the latest version?
http://www.brendangregg.com/dtracebook/index.html

**Comment by sevan** [comment]
Only the iosnoop was newer on that page.
